version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_manager
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth-service:
    build:
      context: ./auth-service
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: task_manager
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  task-service:
    build:
      context: ./task-service
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: task_manager
    depends_on:
      - postgres
    ports:
      - "3001:3001"

volumes:
  postgres-data:
